### ISSUE TITLE
可以请您写一个server的例子吗?

### ISSUE THREAD

**Issue by snow2flying** [quininer/tokio-quiche#1]
您好,最近看了您的这个项目,觉得很好,希望可以研究一下,请问您可以写一个server的列子吗?这样比较方便测试,我试着去写没有写出来,谢谢

**Comment by quininer** [comment]
我不使用这个，我建议你尝试 [quinn](https://github.com/djc/quinn)。

**Comment by snow2flying** [comment]
好的,非常感谢.
顺便问一下,是因为目前quiche实现的不如quinn吗?

**Comment by quininer** [comment]
不，单纯的是没有时间做这个项目（感觉最近这句话说得特别多）。

quiche 和 neqo 都不错。

**Comment by snow2flying** [comment]
明白,您太忙了
希望您有时间可以完善这个项目
